site_name: DACTYL Generation
site_url: !ENV READTHEDOCS_CANONICAL_URL
theme:
  name: "material"
  logo: "assets/icons8-pterodactyl-480.svg"
  palette:
    primary: teal
  favicon: "assets/web/icons8-pterodactyl-color-120.png"
  features:
    - content.code.copy


plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - Tutorials:
      AWS Bedrock: tutorials/bedrock_tutorial.md
      OpenAI: tutorials/openai_tutorial.md
      Anthropic: tutorials/anthropic_tutorial.md
      Mistral: tutorials/mistral_tutorial.md
      Fireworks AI: tutorials/fireworks_tutorial.md
      Gemini: tutorials/gemini_tutorial.md
      Together AI: tutorials/together_tutorial.md
  - API Reference:
    - Google Gemini: API/gemini_generation.md
    - Fireworks AI: API/fireworks_generation.md
    - Anthropic: API/anthropic_generation.md
    - OpenAI: API/openai_generation.md
    - Bedrock: API/bedrock_generation.md
    - Mistral: API/mistral_generation.md
    - Together AI: API/together_generation.md
  - DACTYL Dataset: dataset.md



