site_name: DACTYL Generation
theme:
  name: "material"
  logo: "assets/icons8-pterodactyl-480.svg"
  palette:
    primary: teal
  favicon: "assets/web/icons8-pterodactyl-color-120.png"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - Dataset: dataset.md
  - Prompt Schema: promptschema.md
  - API Reference:
    - Gemini Generation: API/gemini_generation.md
    - DeepSeek Generation: API/deepseek_generation.md
    - Anthropic Generation: API/anthropic_generation.md
    - OpenAI Generation: API/openai_generation.md
    - Bedrock Generation: API/bedrock_generation.md
    - Mistral Generation: API/mistral_generation.md
    - Quick Generation: API/quick.md



