[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dactyl_generation"
version = "1.1.1"
authors = [
    { name="Shantanu Thorat"},
]
description = "LLM helper package to generate texts using batch inference."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "anthropic",
    "litellm",
    "mistralai",
    "numpy",
    "openai",
    "pandas",
    "protobuf",
    "python-dotenv",
    "Requests",
    "tqdm",
    "typing_extensions",
    "google-generativeai",
    "boto3",
    "together >=2.0.0"
]
license = {text = "MIT"}



