# constants to use

# OpenAI constants
SYSTEM = "system"
ROLE = "role"
USER = "user"
CONTENT = "content"
GPT_4o = "gpt-4o"
GPT_4o_MINI = "gpt-4o-mini"
DEEPSEEK_V3 = "deepseek-ai/DeepSeek-V3"


BODY = "body"
MESSAGE = "message"
MESSAGES = "messages"
TEMPERATURE = "temperature"
TOP_P = "top_p"
MODEL = "model"
MAX_COMPLETION_TOKENS = "max_completion_tokens"
CUSTOM_ID = "custom_id"
INPUT_FILE = "input_file"
RESPONSE = "response"
CHOICES = "choices"
RESULT_FILE_ID = "result_file_id"
PROMPTS = "prompts"
PROMPT = "prompt"
TEXT = "text"
RESULT = "result"
PARAMS = "params"
API_CALL = "api_call"
TARGET = "target"
